# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chronovault/access/proto/chronovault_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chronovault/access/proto/chronovault_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2chronovault/access/proto/chronovault_service.proto\x12\x12\x63hronovault.api.v1\x1a\x1cgoogle/protobuf/struct.proto\"2\n\x0e\x43onnectRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x11\n\tsource_ip\x18\x02 \x01(\t\"m\n\x0cWriteRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x11\n\tsource_ip\x18\x02 \x01(\t\x12\x12\n\ncollection\x18\x03 \x01(\t\x12\'\n\x06record\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\"l\n\x0cQueryRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x11\n\tsource_ip\x18\x02 \x01(\t\x12\x12\n\ncollection\x18\x03 \x01(\t\x12&\n\x05query\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\"1\n\rHealthRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x11\n\tsource_ip\x18\x02 \x01(\t2\xef\x02\n\x12\x43hronoVaultService\x12\x46\n\x07\x43onnect\x12\".chronovault.api.v1.ConnectRequest\x1a\x17.google.protobuf.Struct\x12\x43\n\x06Insert\x12 .chronovault.api.v1.WriteRequest\x1a\x17.google.protobuf.Struct\x12\x41\n\x04\x46ind\x12 .chronovault.api.v1.QueryRequest\x1a\x17.google.protobuf.Struct\x12\x43\n\x06\x44\x65lete\x12 .chronovault.api.v1.QueryRequest\x1a\x17.google.protobuf.Struct\x12\x44\n\x06Health\x12!.chronovault.api.v1.HealthRequest\x1a\x17.google.protobuf.Structb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chronovault.access.proto.chronovault_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONNECTREQUEST']._serialized_start=104
  _globals['_CONNECTREQUEST']._serialized_end=154
  _globals['_WRITEREQUEST']._serialized_start=156
  _globals['_WRITEREQUEST']._serialized_end=265
  _globals['_QUERYREQUEST']._serialized_start=267
  _globals['_QUERYREQUEST']._serialized_end=375
  _globals['_HEALTHREQUEST']._serialized_start=377
  _globals['_HEALTHREQUEST']._serialized_end=426
  _globals['_CHRONOVAULTSERVICE']._serialized_start=429
  _globals['_CHRONOVAULTSERVICE']._serialized_end=796
# @@protoc_insertion_point(module_scope)
